const fs = require('fs');
const fsp = fs.promises;
const path = require('path');
const { exec } = require('child_process');
const util = require('util');
const execAsync = util.promisify(exec);

const NGINX_CONF_DIR = path.join(__dirname, '..', '..', 'infrastructure', 'nginx', 'conf.d');
const TUNNEL_DOMAIN = process.env.TUNNEL_DOMAIN || 'twinverse.org';

class NginxService {
    // Generate nginx config for a project
    generateConfig(project, targetContainer) {
        // Nginx will match these domains explicitly, mapping Cloudflare traffic correctly
        const serverNames = [`${project.subdomain}.localhost`, `${project.subdomain}.${TUNNEL_DOMAIN}`, `localhost`, `127.0.0.1`];
        if (project.custom_domain) serverNames.push(project.custom_domain);

        // Use provided targetContainer or fallback to legacy standard name
        let upstreamHost = targetContainer || `orbitron-${project.subdomain}`;
        let upstreamPort = project.port || 3000;

        // For Docker Compose projects: if the compose stack has its own nginx/proxy container,
        // route to that container's internal port (80) instead of the host-mapped port
        if (project.container_id && project.container_id.startsWith('compose-')) {
            try {
                const projectDir = path.join(__dirname, '..', 'deployments', project.subdomain);
                const { execSync } = require('child_process');
                const services = execSync(`cd ${projectDir} && docker compose ps --services 2>/dev/null`, { encoding: 'utf-8' }).trim().split('\n');
                const nginxSvc = services.find(s => s === 'nginx' || s === 'proxy' || s === 'gateway' || s === 'traefik');
                if (nginxSvc) {
                    const containerName = execSync(`cd ${projectDir} && docker compose ps -q ${nginxSvc} | xargs docker inspect -f '{{.Name}}' | sed 's|^/||'`, { encoding: 'utf-8' }).trim();
                    if (containerName) {
                        upstreamHost = containerName;
                        upstreamPort = 80; // Compose nginx listens on 80 internally
                        console.log(`📡 Compose nginx detected: routing to ${upstreamHost}:${upstreamPort}`);
                    }
                }
            } catch (e) { /* Not a compose project or no nginx service — use default */ }
        }

        return `# Auto-generated by Orbitron for: ${project.name}
server {
    listen 80;
    server_name ${serverNames.join(' ')};

    client_max_body_size 50M;

    location / {
        proxy_pass http://${upstreamHost}:${upstreamPort};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_cache_bypass $http_upgrade;

        # Tuning for large Next.js Image Streams
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }
}
`;
    }

    // Add nginx config for a project
    async addProject(project, targetContainer) {
        const configPath = path.join(NGINX_CONF_DIR, `${project.subdomain}.conf`);
        const config = this.generateConfig(project, targetContainer);
        await fsp.writeFile(configPath, config);
        await this.reload(project.subdomain);
    }

    // Remove nginx config for a project
    async removeProject(subdomain) {
        const configPath = path.join(NGINX_CONF_DIR, `${subdomain}.conf`);
        try {
            await fsp.unlink(configPath);
            await this.reload(subdomain);
        } catch (e) {
            if (e.code !== 'ENOENT') throw e;
        }
    }

    // Reload Nginx container
    async reload(subdomain = 'unknown') {
        try {
            await execAsync('docker exec dev-nginx nginx -s reload 2>/dev/null');
            console.log(`✅ nginx reloaded for ${subdomain}`);
        } catch (e) {
            console.error('⚠️ nginx reload failed:', e.message);
        }
    }
}

module.exports = new NginxService();
