const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');
const util = require('util');
const execAsync = util.promisify(exec);

const NGINX_CONF_DIR = path.join(__dirname, '..', '..', 'infrastructure', 'nginx', 'conf.d');

class NginxService {
    // Generate nginx config for a project
    generateConfig(project) {
        // Nginx will match these domains explicitly, mapping Cloudflare traffic correctly
        const serverNames = [`${project.subdomain}.localhost`, `${project.subdomain}.twinverse.org`, `localhost`, `127.0.0.1`];
        if (project.custom_domain) serverNames.push(project.custom_domain);
        return `# Auto-generated by Orbitron for: ${project.name}
server {
    listen 80;
    server_name ${serverNames.join(' ')};

    client_max_body_size 50M;

    location / {
        proxy_pass http://orbitron-${project.subdomain}:${project.port || 3000};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;

        # Tuning for large Next.js Image Streams
        proxy_buffering on;
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }
}
`;
    }

    // Add nginx config for a project
    async addProject(project) {
        const configPath = path.join(NGINX_CONF_DIR, `${project.subdomain}.conf`);
        const config = this.generateConfig(project);
        fs.writeFileSync(configPath, config);
        await this.reload(project.subdomain);
    }

    // Remove nginx config for a project
    async removeProject(subdomain) {
        const configPath = path.join(NGINX_CONF_DIR, `${subdomain}.conf`);
        if (fs.existsSync(configPath)) {
            fs.unlinkSync(configPath);
            await this.reload(subdomain);
        }
    }

    // Reload Nginx container
    async reload(subdomain = 'unknown') {
        try {
            await execAsync('docker exec dev-nginx nginx -s reload 2>/dev/null');
            console.log(`✅ nginx reloaded for ${subdomain}`);
        } catch (e) {
            console.error('⚠️ nginx reload failed:', e.message);
        }
    }
}

module.exports = new NginxService();
