const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const NGINX_CONF_DIR = path.join(__dirname, '..', '..', 'infrastructure', 'nginx', 'conf.d');

class NginxService {
    // Generate nginx config for a project
    generateConfig(project) {
        const serverNames = [`${project.subdomain}.localhost`];
        if (project.custom_domain) serverNames.push(project.custom_domain);
        return `# Auto-generated by Orbitron for: ${project.name}
server {
    listen 80;
    server_name ${serverNames.join(' ')};

    client_max_body_size 50M;

    location / {
        proxy_pass http://orbitron-${project.subdomain}:${project.port || 3000};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }
}
`;
    }

    // Add nginx config for a project
    addProject(project) {
        const configPath = path.join(NGINX_CONF_DIR, `${project.subdomain}.conf`);
        const config = this.generateConfig(project);
        fs.writeFileSync(configPath, config);
        this.reload();
    }

    // Remove nginx config for a project
    removeProject(subdomain) {
        const configPath = path.join(NGINX_CONF_DIR, `${subdomain}.conf`);
        if (fs.existsSync(configPath)) {
            fs.unlinkSync(configPath);
            this.reload();
        }
    }

    // Reload nginx
    reload() {
        try {
            execSync('docker exec dev-nginx nginx -s reload 2>/dev/null', { stdio: 'pipe' });
        } catch (e) {
            console.error('Failed to reload nginx:', e.message);
        }
    }
}

module.exports = new NginxService();
