import os

filepath = '/home/stevenlim/WORK/orbitron/public/changelog-en.html'

replacements = [
    ('<title>Orbitron - 최신 업데이트</title>', '<title>Orbitron - Updates</title>'),
    ('<meta name="description" content="Orbitron의 최신 기능 추가, 버그 수정, 개선 사항을 확인하세요.">', '<meta name="description" content="Check out the latest feature additions, bug fixes, and improvements for Orbitron.">'),
    ('IR (투자 정보)', 'IR (Investors)'),
    ('<h1>🚀 최신 업데이트</h1>', '<h1>🚀 Latest Updates</h1>'),
    ('<p>Orbitron에 새로 추가되거나 개선되는 모든 기능과 변경 사항을 한눈에 확인하세요.</p>', '<p>Check all the newly added or improved features and changes in Orbitron at a glance.</p>'),
    ('2026년 3월 6일', 'March 6, 2026'),
    ('🌐 커스텀 도메인 자동 연결 & 도메인 관리 로드맵', '🌐 Auto Custom Domain Connection & Domain Management Roadmap'),
    ('>신기능<', '>Feature<'),
    ('커스텀 도메인 자동 연결 시스템', 'Custom Domain Auto-Connection System'),
    ('가비아, Namecheap 등에서 구매한 도메인을 3단계(DNS 검증 → Cloudflare 터널 연결 → 활성화)로 자동 연결합니다. CNAME 레코드만 설정하면 SSL 인증서, 리버스 프록시, CDN이 모두 자동 적용됩니다.', 'Automatically connects domains purchased from Gabia, Namecheap, etc. in 3 steps (DNS Verification → Cloudflare Tunnel Connection → Activation). By just setting the CNAME record, SSL certificates, reverse proxy, and CDN are all automatically applied.'),
    ('DNS 자동 검증 API', 'Automated DNS Verification API'),
    ('커스텀 도메인 연결 전 DNS 레코드가 올바르게 설정되었는지 실시간으로 자동 검증합니다. 잘못된 설정 시 구체적인 수정 가이드를 제공합니다.', 'Automatically verifies in real-time whether DNS records are set correctly before connecting a custom domain. Provides specific modification guides for incorrect settings.'),
    ('도메인 관리 가이드 & 구매 기능 로드맵', 'Domain Management Guide & Purchase Feature Roadmap'),
    ('가비아, Namecheap, Cloudflare 등 주요 도메인 등록기관별 CNAME 설정 가이드를 추가했습니다. 향후 도메인 검색/구매/자동 연동 기능(가비아 리셀러 API, Namecheap API)의 구현 로드맵을 공개했습니다.', 'Added CNAME setup guides for major domain registrars like Gabia, Namecheap, and Cloudflare. Revealed the implementation roadmap for future domain search/purchase/auto-connection features (Gabia Reseller API, Namecheap API).'),
    ('2026년 3월 3일', 'March 3, 2026'),
    ('📱 카카오톡 및 텔레그램 모바일 시뮬레이터 & 통합 크로스 인증', '📱 KakaoTalk and Telegram Mobile Simulator & Unified Cross Authentication'),
    ('SSE 탑재 텔레그램 및 카카오톡 모바일 웹 시뮬레이터', 'SSE-Equipped Telegram and KakaoTalk Mobile Web Simulator'),
    ('실제 봇 토큰 없이도 브라우저 내에서 완벽한 프론트엔드 제어를 시연할 수 있도록 <b>RemoteAGT</b> 대시보드 내에 모바일 텔레그램 및 카카오톡 UI 구조를 완벽하게 모사한 웹 시뮬레이터를 런칭했습니다. 폴링 없는 실시간 SSE(Server-Sent Events) 비동기 파이프라인과 Webhook 모킹 기술을 통해 매끄러운 응답 경험을 선사합니다.', 'Launched a web simulator that perfectly mimics the mobile Telegram and KakaoTalk UI structures within the <b>RemoteAGT</b> dashboard so you can demonstrate perfect frontend control in the browser without an actual bot token. Delivers a seamless response experience through a real-time SSE (Server-Sent Events) asynchronous pipeline without polling and Webhook mocking technology.'),
    ('카카오톡 채널 자동 알림봇 연동', 'KakaoTalk Channel Auto Notification Bot Integration'),
    ('이제 배포 진행 상황, 서버 장애 모니터링 경고 등을 텔레그램뿐만 아니라 국내 환경에 맞춘 \'카카오톡 오픈빌더 스킬 연동\'을 통하여 모바일 톡방에서 실시간으로 수신할 수 있습니다.', 'Now, deployment progress and server failure monitoring warnings can be received in real-time in mobile chat rooms through \'KakaoTalk Open Builder Skill Integration\' tailored for the domestic environment, in addition to Telegram.'),
    ('>개선<', '>Improvement<'),
    ('Orbitron & RemoteAGT 크로스오버 통합 인증(SSO)', 'Orbitron & RemoteAGT Crossover Unified Authentication (SSO)'),
    ('이제 완전히 독립된 두 서비스가 물리적인 단일 PostgreSQL 데이터베이스 통신망 위에서 통합되었습니다. 어느 쪽에서 가입하든 <code>*.twinverse.org</code> 와일드카드 쿠키를 통해 완벽한 크로스 호환 로그인이 가능합니다.', 'Now, two completely independent services have been integrated over a single physical PostgreSQL database network. Whichever side you sign up from, fully cross-compatible login is possible through the <code>*.twinverse.org</code> wildcard cookie.'),
    ('>버그수정<', '>Bug Fix<'),
    ('데이터베이스 Schema Column 누락 해결', 'Database Schema Column Missing Resolved'),
    ('가입 시 활동 로그(<code>ragt_audit_log</code>) 로깅 과정에서 <code>web_user_id</code> 및 <code>user_id</code> 컬럼 부재로 발생하던 치명적 로그인 블록 버그를 완벽히 수정 및 마이그레이션 조치했습니다.', 'Completely fixed and migrated the critical login block bug that occurred due to the absence of <code>web_user_id</code> and <code>user_id</code> columns during the activity log (<code>ragt_audit_log</code>) logging process upon sign-up.'),
    ('2026년 3월 2일', 'March 2, 2026'),
    ('🧠 Genius Deployer — 스마트 프로젝트 분석 & 멀티 서비스 배포', '🧠 Genius Deployer — Smart Project Analysis & Multi-Service Deployment'),
    ('Smart Project Analyzer — 프로젝트 구조 자동 분석기', 'Smart Project Analyzer — Automated Project Structure Analyzer'),
    ('배포 시 런타임(Node.js, Python, Go 등), 프레임워크(FastAPI, Vite, Next.js 등 20종+), 서비스 타입, 포트, 빌드 명령어, 의존관계를 100% 자동 감지합니다. orbitron.yaml 없이도 완벽한 배포가 가능합니다.', '100% auto-detects runtimes (Node.js, Python, Go, etc.), frameworks (over 20 types including FastAPI, Vite, Next.js), service types, ports, build commands, and dependencies upon deployment. Perfect deployment is possible even without orbitron.yaml.'),
    ('멀티 서비스 orbitron.yaml 지원', 'Multi-Service orbitron.yaml Support'),
    ('하나의 레포에 백엔드, 프론트엔드, 직원앱 등 여러 서비스를 services 배열로 정의하면 각 서비스를 자동으로 올바른 타겟(Docker/CF Pages)에 배포합니다. <code>from:</code> 참조 문법으로 서비스 간 URL을 자동 연결합니다.', 'By defining multiple services such as backend, frontend, and staff apps as a services array in a single repository, it automatically deploys each service to the correct target (Docker/CF Pages). Automatically connects URLs between services using the <code>from:</code> reference syntax.'),
    ('Cloudflare Pages 정적 사이트 자동 배포', 'Cloudflare Pages Static Site Auto-Deployment'),
    ('<code>type: static</code> 서비스를 감지하면 Cloudflare Pages CDN에 자동 빌드/배포합니다. 전 세계 에지 네트워크에서 초고속으로 서빙되며, 멀티 프론트엔드 동시 배포도 지원합니다.', 'When a <code>type: static</code> service is detected, it automatically builds/deploys to the Cloudflare Pages CDN. Served at ultra-high speed from the global edge network, and also supports simultaneous multi-frontend deployments.'),
    ('PostDeploy 훅 — 배포 후 커스텀 명령 실행', 'PostDeploy Hooks — Execute Custom Commands Post-Deployment'),
    ('orbitron.yaml에 <code>postDeploy:</code> 배열을 정의하여 메인 배포 완료 후 추가 명령어를 자동 실행합니다. 환경변수 주입, 3분 타임아웃, 성공/실패 로그 기록을 지원합니다.', 'Defines the <code>postDeploy:</code> array in orbitron.yaml to automatically execute additional commands after the main deployment is complete. Supports environment variable injection, a 3-minute timeout, and success/failure logging.'),
    ('정적 서비스 빌드 시 환경변수 미주입 수정', 'Fixed Missing Environment Variables During Static Service Build'),
    ('Vite/React 정적 서비스 빌드 시 <code>VITE_API_URL</code> 등 환경변수가 주입되지 않아 프로덕션에서 localhost로 API를 요청하던 크리티컬 버그를 수정했습니다.', 'Fixed a critical bug where environment variables such as <code>VITE_API_URL</code> were not injected during Vite/React static service builds, causing the production environment to request APIs to localhost.'),
    ('배포 문서 5개 페이지 대규모 업데이트', 'Massive Update of 5 Deployment Documentation Pages'),
    ('IaC 가이드, 정적 사이트, AI 분석기, 핵심 개념, 웹 서비스 문서에 멀티 서비스 배포, Smart Analyzer, CF Pages 자동 배포, Error Knowledge DB 내용을 추가했습니다.', 'Added contents on multi-service deployment, Smart Analyzer, CF Pages auto deployment, and Error Knowledge DB to the IaC guide, static sites, AI analyzer, core concepts, and web services docs.'),
    ('Viewer 등급 — 읽기 전용 회원 등급 추가', 'Viewer Tier — Read-Only Member Tier Added'),
    ('신규 가입자는 자동으로 \'Viewer\' 등급이 부여되어, 대시보드 메뉴를 둘러볼 수 있지만 프로젝트 생성·배포·수정은 불가합니다. 관리자가 등급을 승격(Viewer → User → Admin)할 수 있습니다.', 'New users are automatically assigned the \'Viewer\' tier, allowing them to browse the dashboard menu but restricting project creation, deployment, and modification. Administrators can promote their tier (Viewer → User → Admin).'),
    ('2026년 2월 28일', 'February 28, 2026'),
    ('🤖 AI 에러 지식 데이터베이스 & 디스크 최적화', '🤖 AI Error Knowledge Database & Disk Optimization'),
    ('Error Knowledge DB — AI 에러 학습 시스템', 'Error Knowledge DB — AI Error Learning System'),
    ('AI가 분석한 에러 패턴과 해결책을 자동 저장하여, 같은 에러 재발 시 즉시 과거 해결책을 제안합니다. 시간이 지날수록 더 빠르게 문제를 해결하는 학습형 배포 플랫폼입니다.', 'Automatically saves error patterns and solutions analyzed by AI, instantly suggesting past solutions when the same error recurs. A learning deployment platform that resolves issues faster over time.'),
    ('Docker 이미지 HDD 마이그레이션', 'Docker Image HDD Migration'),
    ('Docker 이미지와 빌드 캐시를 SSD에서 HDD로 마이그레이션하여 SSD 디스크 공간을 최적화했습니다. 사이트 성능에 영향 없이 수십 GB의 공간을 확보합니다.', 'Optimized SSD disk space by migrating Docker images and build caches from SSD to HDD. Secures tens of GBs of space without affecting site performance.'),
    ('2026년 2월 22일', 'February 22, 2026'),
    ('📊 대시보드 리소스 모니터링 & 백업 강화', '📊 Enhanced Dashboard Resource Monitoring & Backups'),
    ('프로젝트 카드 실시간 리소스 통계', 'Real-time Project Card Resource Statistics'),
    ('대시보드 프로젝트 목록에서 CPU, 메모리, 업타임, 네트워크 I/O를 실시간으로 확인할 수 있습니다. 개별 페이지 진입 없이 한눈에 모든 프로젝트를 모니터링합니다.', 'Check CPU, memory, uptime, and network I/O in real-time from the dashboard project list. Monitor all projects at a glance without entering individual pages.'),
    ('외부 DB 백업 지원 (DATABASE_URL 기반)', 'External DB Backup Support (Based on DATABASE_URL)'),
    ('PostgreSQL 백업 기능이 확장되어, DATABASE_URL 환경변수로 연결된 외부 데이터베이스도 원클릭 백업이 가능합니다.', 'The PostgreSQL backup feature has been expanded to allow one-click backups of external databases connected via the DATABASE_URL environment variable.'),
    ('미디어 파일 백업 서비스', 'Media File Backup Service'),
    ('프로젝트 내 미디어 파일(이미지, 문서 등)을 DATA 드라이브에 자동 백업합니다. 수동 백업/복원 기능과 배포 시스템 연동을 제공합니다.', 'Automatically backs up media files (images, documents, etc.) within the DATA drive. Provides manual backup/restore functions and deployment system integration.'),
    ('Git 레포 로컬 클론 백업', 'Git Repo Local Clone Backup'),
    ('GitHub URL 옆 \'Clone\' 버튼으로 레포를 로컬 백업 디렉토리에 클론합니다. 이미 존재하면 git pull로 업데이트됩니다.', 'Clones the repo to the local backup directory using the \'Clone\' button next to the GitHub URL. If it already exists, it updates via git pull.'),
    ('2026년 2월 21일', 'February 21, 2026'),
    ('🎯 커밋 선택 배포 & AI 채팅 개선', '🎯 Commit Selection Deployment & AI Chat Improvements'),
    ('특정 커밋 선택 배포', 'Deployment by Specific Commit Selection'),
    ('배포 시 특정 Git 커밋을 선택하여 배포할 수 있습니다. 최신 커밋이 아닌 특정 시점의 코드로 롤백하거나 테스트 배포가 가능합니다.', 'Select a specific Git commit for deployment. Allows rolling back to code from a specific point in time or testing deployments instead of using the latest commit.'),
    ('AI 채팅 API 키 로딩 오류 수정', 'Fixed AI Chat API Key Loading Error'),
    ('AI 채팅 기능에서 "API key missing" 에러와 리셋 버튼 미동작 문제를 해결했습니다. 기본 모델이 Claude 4.6 Sonnet으로 설정됩니다.', 'Resolved the "API key missing" error and unresponsive reset button issue in the AI chat feature. The default model is set to Claude 4.6 Sonnet.'),
    ('요금제 페이지 신규', 'New Pricing Page'),
    ('플랜별 가격, 컴퓨트 비용, 기능 비교 표, 인터랙티브 FAQ 아코디언이 포함된 요금제 페이지를 추가했습니다.', 'Added a pricing page containing prices by plan, compute costs, feature comparison tables, and an interactive FAQ accordion.'),
    ('2026년 2월 20일', 'February 20, 2026'),
    ('🏗 초기 프로덕션 안정화', '🏗 Initial Production Stabilization'),
    ('GitHub Webhook 자동 배포 (CI/CD)', 'GitHub Webhook Auto Deployment (CI/CD)'),
    ('GitHub 레포지토리에 Push하면 자동으로 감지하여 무중단 배포를 실행합니다. Blue-Green 스위칭으로 다운타임 제로를 보장합니다.', 'Automatically detects pushes to the GitHub repository and executes zero-downtime deployments. Guarantees zero downtime with Blue-Green switching.'),
    ('AI 에러 분석 어시스턴트', 'AI Error Analysis Assistant'),
    ('배포 실패 시 Claude/Gemini AI가 에러 로그를 분석하여 한국어로 원인과 해결책을 제시합니다.', 'In case of deployment failure, the Claude/Gemini AI analyzes error logs and provides causes and solutions in English.'),
    ('Unreal Engine 픽셀 스트리밍', 'Unreal Engine Pixel Streaming'),
    ('듀얼 GPU 로드밸런싱이 적용된 Unreal Engine 픽셀 스트리밍 서버를 원클릭 배포합니다.', 'One-click deployment of an Unreal Engine pixel streaming server applied with dual GPU load balancing.'),
    ('>보안<', '>Security<'),
    ('Cloudflare Tunnel 자동 보안 인그레스', 'Cloudflare Tunnel Auto Security Ingress'),
    ('모든 배포 프로젝트에 Cloudflare Tunnel을 통한 HTTPS 보안 접속과 DDoS 방어를 자동 적용합니다.', 'Automatically applies HTTPS secure access and DDoS protection via Cloudflare Tunnel to all deployed projects.'),
    ('📬 새 업데이트를 놓치지 마세요', '📬 Don\'t Miss Out on New Updates'),
    ('Orbitron의 최신 기능을 가장 먼저 경험하세요.', 'Be the first to experience Orbitron\'s latest features.'),
    ('Orbitron 시작하기 →', 'Get Started with Orbitron →'),
    ('>대시보드 관리<', '>Launch Dashboard<'),
    ('프로젝트 내 미디어 파일(이미지, 문서 등)을 DATA 드라이브에 자동 백업합니다. 수동 백업/복원 기능과 배포 시스템 연동을 제공합니다.', 'Automatically backs up media files (images, documents, etc.) within the project to the DATA drive. Provides manual backup/restore functions and deployment system integration.'),
]

if os.path.exists(filepath):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for k, e in replacements:
        content = content.replace(k, e)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Patched {filepath}")
